### ISSUE TITLE
hydro build failing

### ISSUE THREAD

**Issue by 130s** [anqixu/ueye_cam#12]
Just wanted to give headsup that [Hydro DEB build has been failing](https://github.com/anqixu/ueye_cam/issues/new) (as @anqixu might be already aware of).

**Comment by anqixu** [comment]
Builds seem to be finally passing.

http://jenkins.ros.org/view/HbinP32/job/ros-hydro-ueye-cam_binarydeb_precise_i386/90/
http://jenkins.ros.org/view/IbinS32/job/ros-indigo-ueye-cam_binarydeb_saucy_i386/90/

**Comment by dirk-thomas** [comment]
:tada:
