### ISSUE TITLE
Where IS_INIT_EVENT is defined

### ISSUE THREAD

**Issue by JaouadROS** [anqixu/ueye_cam#121]
I couldn't find where [IS_INIT_EVENT](https://github.com/anqixu/ueye_cam/blob/foxy/src/driver/driver.cpp#L1338) object is defined, not in this repository nor in ueye.h header file. Could you point me where I could find it, please ?

**Comment by jmackay2** [comment]
What version of the IDS software suite do you have installed? I checked my version of 4.94 and see it in the ueye.h header file.

**Comment by JaouadROS** [comment]
@jmackay2  I installed the 4.94 version and I found it, thank you.
