### ISSUE TITLE
Incompatibility issue with 4.95.2 IDS SDK

### ISSUE THREAD

**Issue by Delooz** [anqixu/ueye_cam#124]
Hello!
Thanks for this package!
I just wanted to inform that with a UI-3250LE-C-HQ IDS camera, ueye_cam was not working with the ids-software-suite-linux-64-4.95.2 release on an Ubuntu 20.04.4.

Everything compiles and I can start the different ROS nodes without problems. I can use the ueye demo and camera manager without problems as well. However, no image are published on the topic.

After installing the IDS SDK 4.94 as performed in your test, I directly obtained the images on the topic.
I suspect then an incompatibility with the new IDS SDK 4.95.

**Comment by nullket** [comment]
Hello 
>  I suspect then an incompatibility with the new IDS SDK 4.95.

I am running 4.95.**0** on Ubuntu 20.04 with Ethernet cameras and it works fine! The .1 and .2 release should only have minor improvements so no breaking changes (I can currently not upgrade my system to verify this). Thus, I would say that the package works with 4.95 - at least on my computers ;) 


Have you installed the package from the offical ros repos or simply cloned this git to your workspace (I would recommend the latter to make sure you have the newest/current package version)
  

> After installing the IDS SDK 4.94 as performed in your test, I directly obtained the images on the topic.

Was the ueyedaemon maybe not running? Open the cameramanager with root and activate the daemon in case it is not activated. 


If 4.94. is currently working could you please install 4.95 again to verify that it was simply not a issue solved by reinstalling? Please restart you computer after every installation.

> After installing the IDS SDK 4.94 as performed in your test, I directly obtained the images on the topic. 
How are you starting the node? Have you used the same launch file for both sdk versions?


In case all of the above fails, please provide a debug log (setting roslog to debug output BEFORE starting the node) for BOTH SDK Versions

**Comment by Delooz** [comment]
Hello @nullket,
Thanks for your fast reply! 
I reinstalled v4.95.2 and it works now!

Yesterday, I checked the ueyedemon and it was running but I didn't restart my computer.
Restarting was the key of success after all.
Well, sorry for that and thanks for the support!
