### ISSUE TITLE
IS_TIMED_OUT external trigger

### ISSUE THREAD

**Issue by Chris-Bee** [anqixu/ueye_cam#26]
Hello,

I guess this is related to issue #6 The scenario is that I implement a service that sends some information to the camera node and runs the image grep loop till I have one image. I trigger the camera externally and call this service. In this case it needs to check for an image at leased 3 times, with an timeout of 2000ms to get an image. If I minimize the timeout to 40ms I still need to run "get image" around 3 times and I get the image earlier cause of the smaller timeout. Also, I do not trigger again during the image readout.

This tells me that the driver is not really checking for images "during" the timeout.

**Comment by mimicax** [comment]
I'm quite confused by your write-up:
- issue #6 has some actionable suggestions on how to reduce USB bandwidth... if those don't solve the issue, then it might not be related
- "implement a service" -> ROS service server on your own node? or generic RPI service?
- "image grep loop"?
- "not really checking for images during the timeout": not sure what you mean, but as long as there's a subscriber connected, the ueye_cam nodelet will actively attempt to grab frames
- note that the ueye_cam nodelet's spin loop updates at 200Hz, which might be too small for your usages (https://github.com/anqixu/ueye_cam/blob/master/src/ueye_cam_nodelet.cpp#L885) -- try changing it to 1000Hz, compile the code, and test again

Suggestions:
- try connecting your externally-triggered camera using ueyedemo, and check if you are getting frames as intended
- be more concise with the description, and ideally provide some sample code (but try to trim unnecessary logic out before you post)
