### ISSUE TITLE
Runing stereo Ueye_cam

### ISSUE THREAD

**Issue by snakehaihai** [anqixu/ueye_cam#33]
Hi Mr Xu
I`m runing master slave demo. I deleted one camera and running 2 camera under external trigger mode.

-----------------------------------------------------------------------------------------------------------------------
Here are the facts:
I can run two camera at same time using ueyedemo
I can run 2 camera separately and sees the image using both  master slave demo(connect only 1 camera) and rgb8 demo.  By vary delay time in arduino, i can see fps change for both camera

-----------------------------------------------------------------------------------------------------------------------
Here is the problem:
But when I`m running two of them at the same time using  master slave demo, there will only be 1 working. And if i writte separate launch file by copy rgb8 demo and modify the name field. the same problem occur, only 1 camera will be running. 
It seems 2 camera are using one same pipline and somehow they are not able to share it. Have you encounter this problem before?

-----------------------------------------------------------------------------------------------------------------------

Details
launch file

  <launch>
    <node pkg="nodelet" type="nodelet" name="nodelet_manager" args="manager" output="screen" />
    
   
    <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_cam1"
          args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
      <param name="camera_name" type="str" value="cam1" /> 
      <param name="camera_topic" type="str" value="image_raw" />
      <param name="camera_id" type="int" value="1" /> 
      <param name="camera_intrinsics_file" type="string" value="slave1.yaml" /> 
      <param name="camera_parameters_file" type="string" value="" /> 

      <param name="ext_trigger_mode" type="bool" value="True" /> 

      

      <param name="color_mode" type="str" value="mono8" /> 

      <param name="image_width" type="int" value="752" />
      <param name="image_height" type="int" value="480" />
      <param name="image_top" type="int" value="-1" /> 
      <param name="image_left" type="int" value="-1" /> 

      <param name="subsampling" type="int" value="1" /> 
      <param name="binning" type="int" value="1" /> 
      <param name="sensor_scaling" type="double" value="1.0" /> 

      <param name="auto_gain" type="bool" value="True" />
      <param name="master_gain" type="int" value="0" />
      <param name="red_gain" type="int" value="0" />
      <param name="green_gain" type="int" value="1" />
      <param name="blue_gain" type="int" value="16" />
      <param name="gain_boost" type="bool" value="False" />

      <param name="auto_exposure" type="bool" value="False" />
      <param name="exposure" type="int" value="33" /> 

      <param name="auto_white_balance" type="bool" value="True" />
      <param name="white_balance_red_offset" type="int" value="0" />
      <param name="white_balance_blue_offset" type="int" value="0" />
      
      <param name="flash_delay" type="int" value="0" /> 
      <param name="flash_duration" type="int" value="1000" /> 
      
      <param name="auto_frame_rate" type="bool" value="False" /> 
      <param name="frame_rate" type="double" value="15.0" /> 
      <param name="pixel_clock" type="int" value="30" />
    </node>

    <node pkg="nodelet" type="nodelet" name="ueye_cam_nodelet_cam2"
          args="load ueye_cam/ueye_cam_nodelet nodelet_manager">
      <param name="camera_name" type="str" value="cam2" /> 
      <param name="camera_topic" type="str" value="image_raw" />
      <param name="camera_id" type="int" value="2" /> 
      <param name="camera_intrinsics_file" type="string" value="slave2.yaml" /> 
      <param name="camera_parameters_file" type="string" value="" /> 

      <param name="ext_trigger_mode" type="bool" value="True" /> 

      

      <param name="color_mode" type="str" value="mono8" /> 

      
      <param name="image_width" type="int" value="752" />
      <param name="image_height" type="int" value="480" />
      <param name="image_top" type="int" value="-1" /> 
      <param name="image_left" type="int" value="-1" /> 

      <param name="subsampling" type="int" value="1" /> 
      <param name="binning" type="int" value="1" /> 
      <param name="sensor_scaling" type="double" value="1.0" /> 

      <param name="auto_gain" type="bool" value="True" />
      <param name="master_gain" type="int" value="0" />
      <param name="red_gain" type="int" value="0" />
      <param name="green_gain" type="int" value="1" />
      <param name="blue_gain" type="int" value="16" />
      <param name="gain_boost" type="bool" value="False" />

      <param name="auto_exposure" type="bool" value="False" />
      <param name="exposure" type="int" value="33" /> 

      <param name="auto_white_balance" type="bool" value="True" />
      <param name="white_balance_red_offset" type="int" value="0" />
      <param name="white_balance_blue_offset" type="int" value="0" />
      
      <param name="flash_delay" type="int" value="0" /> 
      <param name="flash_duration" type="int" value="1000" /> 
      
      <param name="auto_frame_rate" type="bool" value="False" /> 
      <param name="frame_rate" type="double" value="15.0" /> 
      <param name="pixel_clock" type="int" value="30" />
    </node>
  </launch>

    linux distro: 14.04
    ros distro:indigo
    32 bit or 64 bit os: 64
    ueye camera model:UI1221
    how many ueye cameras:2
    ids ueye driver version:uEye-Linux-4.72-64-bit
    ueye_cam git changeset: no idea 
    code execution / roslaunch procedures:  roslaunch master_slaves_rgb8.launch
    running launch file is ok. shows no error
   after view 2 image by  rosrun rviz rviz  
  output at camera driver shows the error
    execution outputs, for both successful and failed runs
dw@dw-HP-EliteBook-820-G2:~/work_space/ueye_cam/src/ueye_cam/launch$ roslaunch master_slaves_rgb8.launch
... logging to /home/dw/.ros/log/4a3a853a-dd29-11e5-afc8-94659ca2f35a/roslaunch-dw-HP-EliteBook-820-G2-24472.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://dw-HP-EliteBook-820-G2:39521/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.16
 * /ueye_cam_nodelet_slave1/auto_exposure: False
 * /ueye_cam_nodelet_slave1/auto_frame_rate: False
 * /ueye_cam_nodelet_slave1/auto_gain: True
 * /ueye_cam_nodelet_slave1/auto_white_balance: True
 * /ueye_cam_nodelet_slave1/binning: 1
 * /ueye_cam_nodelet_slave1/blue_gain: 16
 * /ueye_cam_nodelet_slave1/camera_id: 1
 * /ueye_cam_nodelet_slave1/camera_intrinsics_file: slave1.yaml
 * /ueye_cam_nodelet_slave1/camera_name: slave1
 * /ueye_cam_nodelet_slave1/camera_parameters_file: 
 * /ueye_cam_nodelet_slave1/camera_topic: left_image_raw
 * /ueye_cam_nodelet_slave1/color_mode: mono8
 * /ueye_cam_nodelet_slave1/exposure: 33
 * /ueye_cam_nodelet_slave1/ext_trigger_mode: True
 * /ueye_cam_nodelet_slave1/flash_delay: 0
 * /ueye_cam_nodelet_slave1/flash_duration: 1000
 * /ueye_cam_nodelet_slave1/frame_rate: 15.0
 * /ueye_cam_nodelet_slave1/gain_boost: False
 * /ueye_cam_nodelet_slave1/green_gain: 1
 * /ueye_cam_nodelet_slave1/image_height: 480
 * /ueye_cam_nodelet_slave1/image_left: -1
 * /ueye_cam_nodelet_slave1/image_top: -1
 * /ueye_cam_nodelet_slave1/image_width: 752
 * /ueye_cam_nodelet_slave1/master_gain: 0
 * /ueye_cam_nodelet_slave1/pixel_clock: 30
 * /ueye_cam_nodelet_slave1/red_gain: 0
 * /ueye_cam_nodelet_slave1/sensor_scaling: 1.0
 * /ueye_cam_nodelet_slave1/subsampling: 1
 * /ueye_cam_nodelet_slave1/white_balance_blue_offset: 0
 * /ueye_cam_nodelet_slave1/white_balance_red_offset: 0
 * /ueye_cam_nodelet_slave2/auto_exposure: False
 * /ueye_cam_nodelet_slave2/auto_frame_rate: False
 * /ueye_cam_nodelet_slave2/auto_gain: True
 * /ueye_cam_nodelet_slave2/auto_white_balance: True
 * /ueye_cam_nodelet_slave2/binning: 1
 * /ueye_cam_nodelet_slave2/blue_gain: 16
 * /ueye_cam_nodelet_slave2/camera_id: 5
 * /ueye_cam_nodelet_slave2/camera_intrinsics_file: slave2.yaml
 * /ueye_cam_nodelet_slave2/camera_name: slave2
 * /ueye_cam_nodelet_slave2/camera_parameters_file: 
 * /ueye_cam_nodelet_slave2/camera_topic: right_image_raw
 * /ueye_cam_nodelet_slave2/color_mode: mono8
 * /ueye_cam_nodelet_slave2/exposure: 33
 * /ueye_cam_nodelet_slave2/ext_trigger_mode: True
 * /ueye_cam_nodelet_slave2/flash_delay: 0
 * /ueye_cam_nodelet_slave2/flash_duration: 1000
 * /ueye_cam_nodelet_slave2/frame_rate: 15.0
 * /ueye_cam_nodelet_slave2/gain_boost: False
 * /ueye_cam_nodelet_slave2/green_gain: 1
 * /ueye_cam_nodelet_slave2/image_height: 480
 * /ueye_cam_nodelet_slave2/image_left: -1
 * /ueye_cam_nodelet_slave2/image_top: -1
 * /ueye_cam_nodelet_slave2/image_width: 752
 * /ueye_cam_nodelet_slave2/master_gain: 0
 * /ueye_cam_nodelet_slave2/pixel_clock: 30
 * /ueye_cam_nodelet_slave2/red_gain: 0
 * /ueye_cam_nodelet_slave2/sensor_scaling: 1.0
 * /ueye_cam_nodelet_slave2/subsampling: 1
 * /ueye_cam_nodelet_slave2/white_balance_blue_offset: 0
 * /ueye_cam_nodelet_slave2/white_balance_red_offset: 0

NODES
  /
    nodelet_manager (nodelet/nodelet)
    ueye_cam_nodelet_slave1 (nodelet/nodelet)
    ueye_cam_nodelet_slave2 (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [24486]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4a3a853a-dd29-11e5-afc8-94659ca2f35a
process[rosout-1]: started with pid [24509]
started core service [/rosout]
process[nodelet_manager-2]: started with pid [24526]
process[ueye_cam_nodelet_slave1-3]: started with pid [24527]
process[ueye_cam_nodelet_slave2-4]: started with pid [24528]
[ INFO] [1456560511.789361974]: Initializing nodelet with 4 worker threads.
[ INFO] [1456560511.865979831]: Unable to open camera calibration file [slave1.yaml]
[ WARN] [1456560512.532831751]: Could not load [slave1]'s sensor parameters file /home/dw/.ros/camera_conf/slave1.ini (IS_FILE_WRITE_OPEN_ERROR)
[ WARN] [1456560512.555851544]: [slave1] does not support internal image scaling
[ INFO] [1456560512.615054419]: UEye camera [slave1] initialized on topic /slave1/left_image_raw
Width:			752
Height:			480
Left Pos.:		-1
Top Pos.:		-1
Color Mode:		mono8
Subsampling:		1
Binning:		1
Sensor Scaling:		1
Auto Gain:		1
Master Gain:		0
Red Gain:		0
Green Gain:		1
Blue Gain:		16
Gain Boost:		0
Auto Exposure:		0
Exposure (ms):		32.9861
Auto White Balance:	1
WB Red Offset:		0
WB Blue Offset:		0
Flash Delay (us):	0
Flash Duration (us):	1000
Ext Trigger Mode:	1
Auto Frame Rate:	0
Frame Rate (Hz):	15.003
Pixel Clock (MHz):	30
Mirror Image Upside Down:	0
Mirror Image Left Right:	0

[ INFO] [1456560512.653306001]: Unable to open camera calibration file [slave2.yaml]
[ WARN] [1456560513.101279536]: Could not load [slave2]'s sensor parameters file /home/dw/.ros/camera_conf/slave2.ini (IS_FILE_WRITE_OPEN_ERROR)
[ WARN] [1456560513.123710240]: [slave2] does not support internal image scaling
[ INFO] [1456560513.183484081]: UEye camera [slave2] initialized on topic /slave2/right_image_raw
Width:			752
Height:			480
Left Pos.:		-1
Top Pos.:		-1
Color Mode:		mono8
Subsampling:		1
Binning:		1
Sensor Scaling:		1
Auto Gain:		1
Master Gain:		0
Red Gain:		0
Green Gain:		1
Blue Gain:		16
Gain Boost:		0
Auto Exposure:		0
Exposure (ms):		32.9861
Auto White Balance:	1
WB Red Offset:		0
WB Blue Offset:		0
Flash Delay (us):	0
Flash Duration (us):	1000
Ext Trigger Mode:	1
Auto Frame Rate:	0
Frame Rate (Hz):	15.003
Pixel Clock (MHz):	30
Mirror Image Upside Down:	0
Mirror Image Left Right:	0

[ INFO] [1456560529.610068289]: [slave1] set to external trigger mode
[ INFO] [1456560536.721729385]: [slave2] set to external trigger mode
[ERROR] [1456560538.721890473]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560538.721934676]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560540.722178980]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560540.722215219]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560542.722422993]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560542.722473447]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560544.722659439]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560544.722695852]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560546.722842196]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560546.722887147]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560548.723238723]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560548.723292800]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560550.723456031]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560550.723502870]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549
[ERROR] [1456560552.723666666]: Timed out while acquiring image from [slave2] (IS_TIMED_OUT)
[ERROR] [1456560552.723707226]: If this is occurring frequently, see https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549

    have you tried opening your cameras using ueyedemo, and seen success/failure frame captures?

**Comment by progtologist** [comment]
It appears to me that your setup is dropping frames for the second camera. I experienced similar issues when I had connected two cameras in the same USB hub. When I moved one of the cameras to a USB3 interface I was able to get consistent FPS for both cameras without problems.
Careful though, IDS cameras only work on USB3 with x86 architecture processors, on ARM, with the current driver, there is no way to get good results on a USB3 controller even with one camera, at least until IDS decides to fix this.

**Comment by anqixu** [comment]
Your roslaunch error messages indeed indicate that slave2 is dropping 1 frame every 2 seconds. This would however mean that you should still be successfully receiving (2*15-1) frames every 2 seconds from slave2. You should confirm this with 'rostopic hz /slave2/right_image_raw' or rosbag, rather than using rviz or image_view.

Given this infrequent rate of dropped frames, I concur with @progtologist that your cameras might be choking a single USB bus. You can try connecting the cameras in separate USB sockets on your HP EliteBook, preferably one on the USB3 bus and one on the USB2 bus. You can run the 'lsusb' terminal command to confirm that these cameras are indeed on separate buses. Also, read through https://github.com/anqixu/ueye_cam/issues/6#issuecomment-49925549 for other potential issues (e.g. long or poor USB cables).

To further debug the situation, I would recommend opening both cameras using ueyedemo, but first ensure that they are operating in external trigger mode and not freerun mode. There should be an alert icon and count in the bottom right corner of the GUI showing how many frames were dropped. You can then get more specific details on why these are being dropped, by choosing one of the menu options (I forgot its name, but it should be something like "Debug Information" or "Frame Information", etc.).

**Comment by snakehaihai** [comment]
Hi anqi
I tried to run them separately with external trigger. Varying delay on arduino have effect on your rgb.launch output FPS. Running solo they are fine with each camera. So positive on external trigger.

using rostopic to echo when running 2 togerther will still result in droping frame.
I use one usb2 one usb3 and result is still the same drop frame. I ensure the camera is running at 2 different bus using lsusb.

ueyedemo external trigger is not working for some reason. as it always go in to free running mode. 
using your node running 2 camera at free running mode seems have no problem. Just that under external trigger, running 2 at the same time will result in drop frame.

Is it possible that you can try to debug using remote VNC so that you can sees the problem

**Comment by anqixu** [comment]
If the USB bus throughput is not the issue, then maybe the underlying IDS driver is choking. Your guess is probably as good as mine.

If you continue having issues, I recommend contacting IDS support staff directly. Although I have some experience using and configuring uEye cameras, I am by no means an expert nor am I affiliated with IDS.

**Comment by TrinhNC** [comment]
@snakehaihai I know it's been quite a long time now but I'm facing exactly the same problem here. Have you found the solution for this?

**Comment by TrinhNC** [comment]
I have found the problem. There is a small bug in the **ueye_cam_nodelet.cpp**, line 213 which put the value of GPIO1 to GPIO2, so both values are always the same. I have created a [pull request](https://github.com/TrinhNC/ueye_cam).

Some of my personal notice (beside others' comment) when dealing with this problem:
My wiring looks like this 

![image](https://user-images.githubusercontent.com/19979949/156653298-3641b6cf-be6a-4e0c-8a80-fabba38abe57.png)

You should carefully check if the wiring is correct. I have mistakenly joined 2 red cables instead of 2 blue cables together and this timeout error also pops up.
I modified the launch file **master_slaves_pwm_rgb8.launch** to match the _camera ID, resolution, frame rate, etc._. So make sure these values are correct.
