### ISSUE TITLE
Release 1.0.13 (or greater)

### ISSUE THREAD

**Issue by 130s** [anqixu/ueye_cam#40]
For me https://github.com/anqixu/ueye_cam/issues/24 on Indigo is a blocker which seems to be addressed in  [a recent commit](https://github.com/anqixu/ueye_cam/issues/32#issuecomment-188449979) that hasn't yet been released.

Thanks!

**Comment by anqixu** [comment]
Release submitted to indigo, jade, and kinetic.

https://github.com/ros/rosdistro/pull/11506
