### ISSUE TITLE
timeout on Odroid

### ISSUE THREAD

**Issue by MaMadDl** [anqixu/ueye_cam#47]
I'm having timeout(IS_TIMED_OUT) for pixel clocks above 16 in odroid xu4 
i tried this [https://github.com/anqixu/ueye_cam/issues/6](url) but still no change 
i have UI-2210SE

**Comment by progtologist** [comment]
I have contacted in the past with IDS and unfortunately the USB3.0 port on the Odroid XU4 is NOT supported. You can use the USB 2.0 port without issues!

**Comment by MaMadDl** [comment]
thank you problem solved
