### ISSUE TITLE
Add xenial armhf to ROS Jenkins buildfarm

### ISSUE THREAD

**Issue by plusk01** [anqixu/ueye_cam#52]
What would it take to add a Jenkins build job for creating an `armhf` deb for Ubuntu 16.04? I'm using a ueye camera on an ODROID XU4 and being able to `apt install ros-kinetic-ueye-cam` on an `armhf` architecture would be so much more convenient.

Thanks for all your work on this project!

**Comment by anqixu** [comment]
https://github.com/ros-infrastructure/ros_buildfarm_config/pull/68

**Comment by plusk01** [comment]
`armhf` added to jenkins job: http://wiki.ros.org/ueye_cam
