### ISSUE TITLE
Add xenial arm64 to ROS Jenkins buildfarm

### ISSUE THREAD

**Issue by plusk01** [anqixu/ueye_cam#57]
Can we add a 64-bit ARM (`arm64`) `ueye_cam` binary to the build farm?

This would make it easier to run on embedded devices such as the Jetson TX1 and TX2.

**Comment by anqixu** [comment]
I support this, but am too swamped to make this change. Please make a pull request and test it with a camera, and I'll approve after testing compilation on my TX2 (i also don't have any ueye cams on hand now)

**Comment by anqixu** [comment]
note that you will need to download the aarch64 IDS drivers, package them to a zip, upload them to ros servers (maybe email Dirk Thomas for help?), and update CMakeLists.txt to use the appropriate ARCH flag and corresponding zip file. See an existing zip file linked in the CMakeLists for which files should be packaged.

**Comment by standmit** [comment]
Does this package works on Jetson TX2 currently?

**Comment by anqixu** [comment]
Still didn't have time to test this nor do I have a uEye camera, sorry :(

**Comment by standmit** [comment]
It works. I launched it 'as is' on Jetson TX2 and got 1440x810 RGB8 at 90 FPS.

**Comment by JadTawil-theonly** [comment]
@plusk01 is support for arm64 available yet?

**Comment by anqixu** [comment]
PR submitted for rosdistro
