### ISSUE TITLE
Not working with robot_upstart ?

### ISSUE THREAD

**Issue by gui2dev** [anqixu/ueye_cam#59]
Hi !

I'm trying to launch nodelet on startup using robot_upstart.
It seems that the nodelet will crash when launched on background.

Here is the link to the robot_upstart issue that I opened: https://github.com/clearpathrobotics/robot_upstart/issues/58

Thanks !

**Comment by anqixu** [comment]
as we discussed on the robot_upstart issue, it seems that the concern is related to the upstart service not finding the library, and not necessarily with ueye_cam itself.
