### ISSUE TITLE
wrong camera id for stereo camera?

### ISSUE THREAD

**Issue by Changliu52** [anqixu/ueye_cam#63]
Hi,
I have a pair of UI1221LE-M camera connected to Nvidia TX2.
I launched the camera node with camera ID 1 and camera ID 2. It can only find the camera ID 1, with the second one throwing the error: 
```
[ERROR] [1512988231.806693548]: Could not open UEye camera ID 2 (IS_CANT_OPEN_DEVICE)
[ERROR] [1512988231.806888683]: Failed to initialize [cam1]
```
Also the camera ID seems to related to sequence of which camera plugged in first. 
So what do I do to ensure the camera I launch is the correct one?

I have also read about https://github.com/anqixu/ueye_cam/issues/48, However I don't know how to run 'ueyecameraconfig' to set camera ID. I don't see any application in such name and terminal complains command not found.

Please help.

Chang

**Comment by anqixu** [comment]
Hi Chang. It sounds like you might have an issue with USB bus contention (i.e. too much data/power throughput on USB bus; and/or poor cabling maybe).

As you read from #48, I suggest you use the non-ROS camera binaries provided by IDS to first make sure that it's not a physical issue with your setup. Assuming that you installed the Linux ARM 64bit hard-float drivers (e.g. `uEyeSDK-4.90.00-ARM_LINUX_IDS_AARCH64_GNU.tgz`), you should be able to find the tools `idscameramanager` and `ueyedemo` in `/usr/local/share/ueye/bin`. I guess part of the issue you ran into was that `ueyecameraconfig` was renamed into `idscameramanager`... By the way, these tools should have been simlinked in `/usr/bin`, so for example you should be able to run the camera GUI by:
* connecting your cameras to the TX2
* open a terminal
* type `ueyedemo`

**Comment by Changliu52** [comment]
Great! Thank you very much @anqixu .
I did used two separate usb ports (USB3 and USB2 OTG)
I ran `idscameramanager` and saw that the both camera has the same camera ID 1 by default.
I was able to change the camera ID in `idscameramanager` and everything worked.

Thank you again for your help.
