### ISSUE TITLE
Unable to change the resolution of the camera without cropping the image

### ISSUE THREAD

**Issue by JaouadROS** [anqixu/ueye_cam#67]
I'm using `bayer_rggb_image_proc.launch` file in which I'm keeping the `image_width` and `image_height` to the maximum resolution of the camera. I want to downsample the resolution of the camera to the half so I set `subsampling` parameter to 2. However I'm getting the error of `Failed to set Area Of Interest`.
I can successfully do the same with `ueyedemo` and getting the resolution I want. What could be the issue here?

Camera: UI527xCP-C
ROS: melodic
Ubuntu: 18.04 LTS

Error:
```
[ERROR] [1527079605.090495031]: Failed to set Area Of Interest (AOI) to 2056 x 1542 with top-left corner at (0, 0) for [camera]
[ERROR] [1527079605.090617499]: Failed to initialize [camera]
```

**Comment by nullket** [comment]
I know this is late, but I am cleaning a bit the repo and closing old issues. This is just the way IDS Cameras work. The `image_width/height` parameters set something like "the pixels on the sensor" being used to acquire the image. `subsampling` would be the way to go. Anyway, as this is older, I hope you have solved it.
