### ISSUE TITLE
adjust exposure parameter

### ISSUE THREAD

**Issue by dean36995** [anqixu/ueye_cam#73]
Sorry, I just adjust the exposure parameter, but it doesn't work. I used ROS kinetic version to change the parameter in "bayer_rggb_image_proc.launch" file, but only the image size and color mode can change. Do you have any method to control the image exposure? Thank you very much.

**Comment by anqixu** [comment]
Maybe your uEye camera does not support changing exposure? Also, make sure to turn off auto-exposure + auto-framerate, and note also that the upper limit of exposure value is bound by the pixel clock and frame rate of your camera.

To verify the above, try changing settings using IDS's `ueyedemo` executable. If it works there, please paste all messages (INFO, WARNING, ERROR) that you get when you `roslaunch ...`.

**Comment by dean36995** [comment]
1. 
I can “use ueye properties” tool when I type the command “ueyedemo” in terminal, then I cancel the “auto” selection which below the “Exposure”, and I can adjust the Exposure parameter by move the “Exposure” bar.
As Feature.1 and Feature.2. To prove the uEye camera can support changing exposure.
 
![0130_exposure34 94](https://user-images.githubusercontent.com/47131199/51960236-1a353d80-2493-11e9-8815-629bb36a8645.png)


Feature. 1
 
![0130_exposure106](https://user-images.githubusercontent.com/47131199/51960240-1e615b00-2493-11e9-947d-aa248dc3067e.png)


Feature. 2
2.
I change the parameter “width:1280”, “height:720”, “auto_exposure: False”, “auto frame_rate: False” in “xs_bayer_rggb.lunch” file, and run the command “roslaunch ueye_cam xs_bayer_rggb.launch”. As below.


roslaunch ueye_cam xs_bayer_rggb.launch 
... logging to /home/ubuntu/.ros/log/f6755f08-243b-11e9-bce0-00044ba7ed11/roslaunch-tegra-ubuntu-30662.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://tegra-ubuntu:45833/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /ueye_cam_nodelet/auto_exposure: False
 * /ueye_cam_nodelet/auto_frame_rate: False
 * /ueye_cam_nodelet/auto_gain: True
 * /ueye_cam_nodelet/auto_white_balance: True
 * /ueye_cam_nodelet/binning: 1
 * /ueye_cam_nodelet/blue_gain: 16
 * /ueye_cam_nodelet/camera_id: 0
 * /ueye_cam_nodelet/camera_intrinsics_file: 
 * /ueye_cam_nodelet/camera_name: camera
 * /ueye_cam_nodelet/camera_parameters_file: /home/ubuntu/catk...
 * /ueye_cam_nodelet/camera_topic: image_raw
 * /ueye_cam_nodelet/color_mode: bayer_rggb8
 * /ueye_cam_nodelet/exposure: 33
 * /ueye_cam_nodelet/ext_trigger_mode: False
 * /ueye_cam_nodelet/flash_delay: 0
 * /ueye_cam_nodelet/flash_duration: 1000
 * /ueye_cam_nodelet/flip_lr: False
 * /ueye_cam_nodelet/flip_upd: False
 * /ueye_cam_nodelet/frame_rate: 30.0
 * /ueye_cam_nodelet/gain_boost: False
 * /ueye_cam_nodelet/green_gain: 1
 * /ueye_cam_nodelet/image_height: 720
 * /ueye_cam_nodelet/image_left: 0
 * /ueye_cam_nodelet/image_top: 0
 * /ueye_cam_nodelet/image_width: 1280
 * /ueye_cam_nodelet/master_gain: 0
 * /ueye_cam_nodelet/output_rate: 0.0
 * /ueye_cam_nodelet/pixel_clock: 30
 * /ueye_cam_nodelet/red_gain: 0
 * /ueye_cam_nodelet/sensor_scaling: 1.0
 * /ueye_cam_nodelet/subsampling: 1
 * /ueye_cam_nodelet/white_balance_blue_offset: 0
 * /ueye_cam_nodelet/white_balance_red_offset: 0

NODES
  /
    nodelet_manager (nodelet/nodelet)
    ueye_cam_nodelet (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [30672]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f6755f08-243b-11e9-bce0-00044ba7ed11
process[rosout-1]: started with pid [30688]
started core service [/rosout]
process[nodelet_manager-2]: started with pid [30706]
process[ueye_cam_nodelet-3]: started with pid [30707]
[ INFO] [1548817559.458768172]: Initializing nodelet with 6 worker threads.
[ WARN] [1548817574.002460811]: [camera] does not support internal image scaling
[ WARN] [1548817574.003219995]: [camera] does not support auto gain mode (IS_NOT_SUPPORTED)
[ WARN] [1548817574.003538018]: Auto frame rate mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817574.003796040]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817574.333316191]: Failed to set white balance red/blue offsets to 0 / 0 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817575.803331791]: [camera] does not support auto gain mode (IS_NOT_SUPPORTED)
[ INFO] [1548817575.930840926]: UEye camera [camera] initialized on topic /camera/image_raw
Width:			1280
Height:			720
Left Pos.:		0
Top Pos.:		0
Color Mode:		bayer_rggb8
Subsampling:		1
Binning:		1
Sensor Scaling:		1
Auto Gain:		0
Master Gain:		0
Red Gain:		0
Green Gain:		1
Blue Gain:		16
Gain Boost:		0
Auto Exposure:		0
Exposure (ms):		33
Auto White Balance:	1
WB Red Offset:		0
WB Blue Offset:		0
Flash Delay (us):	0
Flash Duration (us):	1000
Ext Trigger Mode:	0
Auto Frame Rate:	0
Frame Rate (Hz):	11.6307
Output Rate (Hz):	0
Pixel Clock (MHz):	30
Mirror Image Upside Down:	0
Mirror Image Left Right:	0




3.
I used “rosrun image_raw image_raw image:=/camera/image_raw” command to show the image. As Feature. 3 
![exposure10](https://user-images.githubusercontent.com/47131199/51960250-3042fe00-2493-11e9-8d37-5d5d8baecbd5.png)

Feature. 3

4. 
And adjust the parameter by the rqt_reconfigure. 
“rosrun rqt_reconfigure rqt_reconfigure”
Video link: https://youtu.be/C09A7ZUYO44

And the terminal which running the command “roslaunch ueye_cam xs_bayer_rggb.launch” will show the information as below.

[ INFO] [1548817576.039447923]: [camera] set to free-run mode
[ WARN] [1548817591.303097267]: Auto frame rate mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817591.303299192]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817592.738460195]: Failed to set white balance red/blue offsets to 0 / -1 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817593.340715178]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817599.806434163]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817600.220218314]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817609.070650039]: Auto frame rate mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817609.070888316]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817609.505055868]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817614.792475627]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817615.184954936]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817618.108345580]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817618.537584227]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817622.886191360]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817623.264231338]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ INFO] [1548817725.643606915]: [camera] set to standby mode
[ INFO] [1548817727.529675831]: [camera] set to free-run mode
[ WARN] [1548817739.047917404]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817739.500607165]: Failed to set white balance red/blue offsets to -28 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817743.626604079]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817744.057409280]: Failed to set white balance red/blue offsets to 0 / -4 for [camera] (IS_ACCESS_VIOLATION)
[ WARN] [1548817747.145798924]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817784.004717766]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817785.565771768]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817786.931752397]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817787.621384174]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817789.464339543]: Auto frame rate mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817791.749935900]: Auto frame rate mode is not supported for [camera] (IS_NOT_SUPPORTED)
[ WARN] [1548817793.739416582]: Auto exposure mode is not supported for [camera] (IS_NOT_SUPPORTED)

5. 
I also change the parameter in launch file.
Image “width:1280”, “hight:720”, “auto exposure: False”, “auto frame rate: False”.
Feature. 4 parameters is “exposure:1” “frame rate: 30”.
Feature. 5 parameters is “exposure:33” “frame rate: 30”.
These two features like the same.

 
![xs_exposure1_framerate30](https://user-images.githubusercontent.com/47131199/51960272-523c8080-2493-11e9-9425-10b84d29ca83.png)

Feature. 4
 
![xs_exposure33_framerate30](https://user-images.githubusercontent.com/47131199/51960275-55377100-2493-11e9-8d45-dd774651d199.png)

Feature. 5
6. Other information:
Camera_ini
 
![ueyedemo_vs_camerea_ini](https://user-images.githubusercontent.com/47131199/51960302-71d3a900-2493-11e9-8b52-5099f7513a3a.png)

I try to run the other launch file. “bayer_rggb_image_proc”. But the performance like the “xs_bayer_rggb.lunch” file.


If there is not enough information, please let me know. 
Thank you very much.

**Comment by dean36995** [comment]
Sorry, excuse me.
this kind of camera can set "fixed" focal length?

**Comment by anqixu** [comment]
I don't think so, but you should check with the camera vendor to be sure.

**Comment by nullket** [comment]
As this issue has stalled, I am closing it to clean up the repo a bit. Hope your issue was solved, if not feel free to open a new issue and include debugging information.
